---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: db-creds
  namespace: default
spec:
  encryptedData:
    password: AgCB+Is57lYMm1jNcF0ClHWNzFZrarx5eADJoFdYRBqyIgbtJqSFYN9qBPNvwLYQGBy8GslOrQ3M5xfV0fnPGoPu8eSmMp4AEBxzg8Fv1rGIjwQYw4JVLLC3Vw6SF1bIsQz9jigkIAvwsEq12M2B5m74qU71NXw+uVFgMPI9fC3qSiJnt5L3BQRq2DxcYVivEYYmqU0pqBE8yrQdaASi94PH9GbDOJx6Pv6xcGzfwKwwCuWrsO8Do3CsmUsP/B2WYvTjeyaTPFftSYUHtzy7KJsg48OcBnXHBuYXLcZrneoxvivf/68bI0M9GOwrrdymo5Qq781rWCyp9qRPAOXDtytsAgT3TmElna0JcEZS/VtjjJ6Gs9g5DrKmkcDFGBF+bJRPIqeXaMXDoNI3PO7EOkD0qRqSB/Cz4zdehhtX1787Xao31BxFNYc3eQEImM1ERd/qLCkBmJNAyi1iWLgEacJzKKqGioe3+aWZZdNjVPRNTtuzVBdfOxiTkw8UcwFPdySVNR8Z9YXYr74qkU2GZce4p0PC9iAXgjEqChHfigVvLPRGcKU++OcZ6lhwtsOews8djb6PYbq8svlyrrx1AK/OA3SfR6le5iyYi2O/eOqyZsGAVbS4u3a+n7p9vpwtFu1StMFCo75owNEJQZwFCwShZhuoJoNHtQi/IvYqrD3EX8WXYKs4zO2tpy5+vWrutwp6ltZ+PGej
    username: AgAF6ehuAPxeRQRdOTMONvFyM3BO6W7FHEqB0KwzUop2EgkRJCNtk8ru4Y0J8a3Fn69nFYQGpgFrnJOv6sCAIrpzk1LfM+PIOumPdCRYCKIA8sAAYl2iTMqfWymqDqwqtiC+VIQa8Xgmkx3x+AkA1WFKdeo6wzYX4EKRJFVt/GZZbjWR9TJCdPjnGoGmnbv1WV20Mf1qtLZST7DJJrj1L1y1hHrtOslaGIRxaeqEsMhWGgq9CraU5c3XUkD4GNjWrenv7BfKVP/oAb16dyouL9JVE/muiHtWoHV7bAu/vyjM/6evZ7XXHHPwqf6wwq3UH+6NUuqlXoVFUvaVUBBKNG4teWLXKJJu/hAoao2u+AQn22KGSKjF4uTxqJBTfMyhVGmzRw16HYtTQ5UmrnauWgNfskogmRsfjwcQ6b5E+8gXEl7lfwbWxeddzWRSrseV4pS/I6CWuxrs9IsqCHTOXrOrgQd06U1WstROjSNa6jFCarxFwnIODWATw7hRLA4S6kjqAO60TIuQlKos7k30QXK6xrIKh5fOICW4sQ6GYa7RsHJsO/OJTG1oYeYbzpjQks/lYpz1I3TQBXo9/YxsESom8cpZkYSopr4AbY0F/rAAFbEjde6T/CoFrc0mKKivTa2YaNAdJP4q6mR7ivuQLXmaH89QxTjIrZBFgiR6Xyc3U7bfls81ZIJqZ7Y2JitiR6AF/kk26Q==
  template:
    metadata:
      creationTimestamp: null
      name: db-creds
      namespace: default
